config/routes.rb
match '404', to: 'us_errors#error_404', via: [:get]
match '500', to: 'us_errors#error_500', via: [:get]

get 'easy_perplex', controller: :easy_perplex, action: :easy_perplex
get 'easy_perplex_actions(/:user_id)', controller: :easy_perplex, action: :easy_perplex_actions, user_id: /\d+/

get 'attachments/download/all/:id', controller: :attachments, action: :download_all

get 'projects/:id/not_member_principal', controller: :projects, action: :not_member_principal

app/controllers/easy_perplex_controller.rb
class EasyPerplexController < ApplicationController
  before_action :require_login
  before_action :check_ldap_installed, only: [:easy_perplex, :easy_perplex_actions]

  if Redmine::Plugin.installed?(:ldap_users_sync)
    include LdapApplicationHelper
    helper LdapApplicationHelper
  end

  def easy_perplex
    @unders = User.current.subordinates(true).sorted
    if (User.current.id == 69)
      @unders = User.find(10).subordinates(true).sorted
    end
    if (@unders.nil? || @unders == [])
      flash[:error] = l(:text_usability_easy_perplex_no_subordinates)
      @unders = nil
      return
    end
  end

  def easy_perplex_actions
    if (params[:user_id].to_i == 0)
      @clear = true
      return
    end

    @subordinate = User.active.where(id: params[:user_id].to_i).first
    if (@subordinate.nil?)
      flash[:error] = l(:text_usability_easy_perplex_wrong_user)
      return
    end
    if User.current.subordinates(true).where(id: @subordinate.id).blank?
      flash[:error] = l(:text_usability_easy_perplex_does_not_subordinate, user: view_context.link_to_user(@subordinate)).html_safe
      return
    end

    prepare_projects_for_actions
    prepare_departments_and_types_for_actions
  end

  private

  def check_ldap_installed
    unless Redmine::Plugin.installed?(:ldap_users_sync)
      flash[:error] = l(:text_usability_easy_perplex_ldap_was_not_installed)
      render action: :easy_perplex
    end
  end

  def prepare_projects_for_actions
    roles = Setting.plugin_usability['easy_perplex_executor_roles']
    if roles && roles.is_a?(Array) && roles.any? && !roles[0].blank?
      @projects = Project.active.joins({ memberships: :roles }).where("#{Member.table_name}.user_id = ? and #{Role.table_name}.id in (?)", @subordinate.id, roles)
    else
      @projects = @subordinate.projects.active.visible
    end
    @projects = @projects.joins("LEFT JOIN #{Member.table_name} m on m.project_id = #{Project.table_name}.id and m.user_id = #{User.current.id}")
                         .select("#{Project.table_name}.*, case when m.id is null then 0 else 1 end as is_participant")
                         .distinct
  end

  def prepare_departments_and_types_for_actions
    @department = false
    return unless (Redmine::Plugin.installed?(:service_desk))

    @department = nil

    top_department = @subordinate.user_department.head_of_branch ? @subordinate.user_department : @subordinate.top_department

    if (sd = SdRequestType.where('user_department_id = ?', top_department.id)) != [ ]
      @department = { head: top_department, branch: @subordinate.user_department, types: sd }
    end
  end
end

app/controllers/us_errors_controller.rb
class UsErrorsController < ApplicationController

  before_action :check_users

  def error_500
    render_custom_error(500)
  end

  def error_404
    render_custom_error(404)
  end

  protected

  def render_custom_error(status=500)
    @err_msg = us_exception ? us_exception.message : ''
    @err_info = us_exception ? us_exception.backtrace.join("\n") : ''
    @status = status

    respond_to do |format|
      format.html { use_layout ? render(template: 'errors/error_status', layout: false, status: status) : render(template: 'errors/error_status_no_layout', layout: false, status: status) }
      format.all { render nothing: true, status: status }
    end
  end

  def us_exception
    @ex ||= env['action_dispatch.exception']
  end

  private

  def check_users
    @users = []
    if Setting.plugin_usability['users_at_error'].is_a?(Array)
      users_ids = Setting.plugin_usability['users_at_error'].map(&:to_i)
      @users = User.where(id: users_ids).active if users_ids.any?
    end
  end

end

app/helpers/usability_helper.rb
module UsabilityHelper
  def us_email_issue_attributes(issue, user)
    items = []
    %w(author status priority assigned_to category fixed_version).each do |attribute|
      unless issue.disabled_core_fields.include?(attribute + "_id")
        items << [l("field_#{attribute}"), issue.send(attribute)]
      end
    end
    issue.visible_custom_field_values(user).each do |value|
      items << [value.custom_field.name, show_value(value, false)]
    end
    items
  end

  def us_available_progress_styles(object, field_name, current_value, options={})
    if object.is_a?(String) || object.is_a?(Symbol)
      object = object.to_s
    else
      object = model_name_from_record_or_class(object).param_key
    end

    select_options = [
        [l(:usability_pb_std),'std'],
        [l(:usability_pb_tiny),'tiny'],
        [l(:usability_pb_pie),'pie'],
        [l(:usability_pb_tor),'tor']
    ]
    if options.present? && options[:allow_blank]
      select_options.unshift ['x', '']
    end

    select_tag "#{object}[#{field_name.to_s}]", options_for_select(select_options, current_value)
  end
end

app/views/attachments/_form.html.erb
<%= rmp_render_previous('attachments/form', __FILE__, true, local_assigns || {}) %>

<script type="text/javascript" charset="utf-8">
  if(typeof original_addInlineAttachmentMarkup !== 'function'){
    var original_addInlineAttachmentMarkup = addInlineAttachmentMarkup;
    addInlineAttachmentMarkup = function(file){
        var return_value = original_addInlineAttachmentMarkup.apply(this, [{type: file.type, name: file.name.split(' ').join('_')}]);
        return return_value;
    };
  }
</script>

app/views/attachments/upload.js.erb
var fileSpan = $('#attachments_<%= j params[:attachment_id] %>');
<% if @attachment.new_record? %>
  fileSpan.hide();
  alert("<%= escape_javascript @attachment.errors.full_messages.join(', ') %>");
<% else %>
fileSpan.find('input.token').val('<%= j @attachment.token %>');
fileSpan.find('a.remove-upload')
  .attr({
    "data-remote": true,
    "data-method": 'delete',
    href: '<%= j attachment_path(@attachment, :attachment_id => params[:attachment_id], :format => 'js') %>'
  })
  .off('click');

  fileSpan.find('.filename').val(fileSpan.find('.filename').val().split(' ').join('_'));
<% end %>

app/views/easy_perplex/_easy_perplex_actions.html.erb
<% unless (@subordinate.nil?) %>
  <fieldset>
    <legend><strong><%= l(:label_usability_easy_perplex_issues_header) %></strong></legend>
    <p><span><%= l(:label_usability_easy_perplex_issues_description, user: link_to_user(@subordinate)).html_safe %></span></p>
    <% projects = @projects.select { |it| it.attributes['is_participant'].to_i == 1 } || [] %>
    <% if @projects == [] %>
      <div class="nodata" style="margin-bottom: 0px; padding-left: 4px; text-align: left;">
        <%= l(:text_usability_easy_perplex_subordinate_is_not_participant_of_any_project, user: link_to_user(@subordinate)).html_safe %>
        <div style='padding-top: 5px;'>
          <%= render partial: 'user_for_help' %>
        </div>
      </div>
    <% elsif projects == [] %>
      <div class="nodata" style="margin-bottom: 0px; padding-left: 4px; text-align: left;">
        <%= l(:text_usability_easy_perplex_you_are_not_participant_of_any_project, user: link_to_user(@subordinate)).html_safe %>
        <div style='padding-top: 5px;'>
          <%= render partial: 'user_for_help' %>
        </div>
      </div>
    <% else %>
      <% projects.each do |it| %>
        <div style="margin-bottom: 5px"><%= link_to "<span>#{l(:label_usability_easy_perplex_create_issue, project: it.name, user: @subordinate)}</span>".html_safe, { controller: :issues, action: :new, project_id: it.identifier, executor_id: @subordinate.id, easy_perplex: true }, class: 'no_line' %></div>
      <% end %>
    <% end %>
  </fieldset>
  <% if @department != false %>
    <fieldset>
      <legend><strong><%= l(:label_usability_easy_perplex_sd_requests_header) %></strong></legend>
      <p><span><%= l(:label_usability_easy_perplex_sd_requests_description, user: link_to_user(@subordinate)).html_safe %></span></p>

      <% if @department.is_a?(Hash) && !@department[:types].nil? %>
        <%= link_to "<span>#{l(:label_usability_easy_perplex_create_request, department: @department[:head].name)}</span>".html_safe, { controller: :sd_requests, action: :new, easy_perplex: true, executor_id: @subordinate.id, head_id: @department[:head].id, branch_id: @department[:branch].try(:id) }, class: 'al-btn al-btn-success no_line' %>
      <% else %>
        <div class="nodata" style="margin-bottom: 0px; padding-left: 4px; text-align: left;">
          <%= l(:text_usability_easy_perplex_subordinate_is_not_participant_of_any_service_desk, user: link_to_user(@subordinate)).html_safe %>
          <div style='padding-top: 5px;'>
            <%= render partial: 'user_for_help' %>
          </div>
        </div>
      <% end %>
    </fieldset>
  <% end %>
<% end %>

app/views/easy_perplex/_easy_perplex_modal.html.erb
<div class='modal-header'>
  <button type='button' class='us_close' data-dismiss='modal' aria-hidden='true'>&times;</button>
  <h3><%= l(:label_usability_easy_perplex_modal_header) %></h3>
</div>
<div class='modal-body'>
  <%= form_tag url_for({ action: :easy_perplex_actions }), id: 'us_subordinate_form', method: :get, remote: true do %>
    <div class='us-perplex-tabular'>
      <label for='user_id'><%= l(:label_usability_easy_perplex_subordinate) %></label>
      <span><%= l(:label_usability_easy_perplex_subordinate_description) %>:</span>
      <%= select_tag 'user_id', options_for_select(@unders.collect { |it| [it.name, it.id] }), include_blank: true, id: 'us-subordinates-select2', style: 'width: 100%' %>
      <!-- <div id="us-perplex-loader" style="display: inline;">&nbsp;&nbsp;&nbsp;&nbsp;</div> -->
    </div>
  <% end %>

  <div id="us-perplex-actions" class="us-perplex-actions"></div>
</div>
<div class="modal-footer">
  <%= button_tag l(:label_usability_easy_perplex_modal_cancel), 'aria-hidden' => 'true',  'data-dismiss' => 'modal' %>
</div>

app/views/easy_perplex/_user_for_help.html.erb
<% if Redmine::Plugin.installed?(:ldap_users_sync) %>
  <% users = (Setting.plugin_usability || {})['users_at_error'] %>
  <% if users.is_a?(Array) && users.any? %>
    <%= l(:label_usability_easy_perplex_contact_to) %>:
    <% User.where(id: users.map(&:to_i)).each do |u| %>
      <%= show_user_info(u) %>
    <% end %>
  <% end %>
<% end %>

app/views/easy_perplex/easy_perplex.js.erb
RMPlus.Usability.show_flashes('<%= flash[:error] %>', '<%= flash[:notice] %>')
<% flash.delete(:error); flash.delete(:notice) %>

<% if (!@unders.nil? && @unders != [ ]) %>
  $('#easy-perplex-modal-window').html("<%= escape_javascript(render partial: 'easy_perplex_modal') %>");
  $('#us-subordinates-select2').select2({
    placeholder: '<%= l(:label_usability_easy_perplex_select_subordinate) %>',
    allowClear: true
  });
  $(window).trigger("resize");
<% end %>

app/views/easy_perplex/easy_perplex_actions.js.erb
RMPlus.Usability.show_flashes('<%= flash[:error] %>', '<%= flash[:notice] %>')
<% if (flash[:error] || flash[:notice]) %>
  $('#easy-perplex-modal-window').modal('hide');
<% else %>
  $('#us-perplex-actions').html("<%= escape_javascript(render partial: 'easy_perplex_actions') %>");
<% end %>
<% flash.delete(:error); flash.delete(:notice) %>

app/views/hooks/usability/_body_bottom.html.erb
<div id="BS_Modal" class="modal I fade" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true" style="z-index: 1060; display: none;">
  <div class="modal-header">
    <h3 id="myModalLabel">Modal header</h3>
  </div>
  <div class="modal-body">
    <p>One fine body…</p>
  </div>
  <div class="modal-footer">
    <button class="btn" data-dismiss="modal" aria-hidden="true"><%= l(:label_usability_close) %></button>
    <button class="btn btn-primary"><%= l(:button_save) %></button>
  </div>
</div>

<div id="easy-perplex-modal-window" class="modal hide fade" style="width: 500px; z-index: 1061; display: none;" data-width="500px" data-height="90%" aria-hidden="true" role="dialog">
</div>
<% if controller_name == 'news' && (action_name == 'index' || action_name == 'show') && @news.is_a?(News) %>
  <p id="us-is-uncommentable">
    <label for="news_is_uncommentable"><%= l(:label_news_uncommentable) %></label>
    <%= check_box 'news', 'uncommentable', {}, 'true', 'false' %>
  </p>
  <script type="text/javascript">
    $(document).ready(function(){
      var p_is_uncommentable = $('#us-is-uncommentable').remove();
      if ($('#news_summary').length > 0){
        $('#news_summary').parent().after(p_is_uncommentable);
      }
    });
  </script>
<% end %>

<% if controller_name == 'news' && action_name == 'show' && @news && @news.try(:uncommentable) %>
  <script type="text/javascript">
    $(document).ready(function(){
      $('.comments').after("<p style = 'font-style: italic;'><%= l(:message_news_uncommentable) %></p>");
    });
  </script>
<% end %>

<% if @us_add_async_tabs && @project %>
  <%
    all_tabs = project_settings_tabs_without_usability
    r = all_tabs.select { |it| it[:name] == 'info' || it[:name] == params[:tab] }
    r = [all_tabs.first] if r.blank?
    all_tabs.reject! { |it| r.include?(it) }
  %>
  <% if all_tabs.present? %>
    <script type="text/javascript" charset="utf-8">
      <% all_tabs.each do |tab| %>
        RMPlus.Usability.add_async_project_tab('<%= tab[:name] %>', '<%= @project.identifier %>');
      <% end %>
    </script>
  <% end %>
<% end %>

app/views/hooks/usability/_html_head.html.erb
<meta name="viewport" content="width=device-width, initial-scale=1"/>
<% settings = (Setting.plugin_usability || {}) %>
<script type="text/javascript">

  RMPlus.Usability = (function(my){
    var my = my || {};
    <% if settings['use_autosave_fields'] %>
      my.msg_autosaved = '<%= escape_javascript(l(:label_usability_was_autosaved)) %>';
    <% end %>
    <% if settings['collapse_changes_for_history'] %>
      my.collapse_label = '<%= l(:label_usability_collapse_history) %>';
      my.expand_label = '<%= l(:label_usability_expand_history) %>';
    <% end %>
    my.settings = <%= settings.to_json.html_safe %>;

    my.galleryPopupSettings = {
      type: 'image',
      gallery: {
        enabled: true,
        navigateByImgClick: true,

        midClick: false,

        arrowMarkup: '<button title="%title%" type="button" class="mfp-arrow mfp-arrow-%dir%"></button>',
        tPrev: '<%= l(:magnificPopup_tPrev) %>',
        tNext: '<%= l(:magnificPopup_tNext) %>',
        tCounter: '<%= l(:magnificPopup_tCounter).html_safe %>'
      },
      image: {
        tError: '<%= l(:magnificPopup_tError).html_safe %>'
      },
      ajax: {
       tError: '<%= l(:magnificPopup_ajax_tError).html_safe %>'
      },
      tClose: '<%= l(:magnificPopup_tClose) %>',
      tLoading: '<%= l(:magnificPopup_tLoading) %>'
    };

    return my;
  })(RMPlus.Usability || {});

  <% if settings['custom_help_url'].to_s != '' %>

    $(document).ready( function () {
      $("#top-menu a.help:first").attr("href", "<%= settings['custom_help_url'] %>");
    });

  <% end %>

<% if settings['hide_toolbar_for_wiki_textareas'] %>
  $(document).ready( function () {
    $(document.body).on('click', 'textarea.wiki-edit', function(event) {
        $(event.target).parent().prev('.jstElements').show();
        });
    $(document.body).on('blur', 'textarea.wiki-edit', function(event) {
      setTimeout(function(){
        if ($(event.target)[0] !== document.activeElement){
          $(event.target).parent().prev('.jstElements').animate({opacity: 0}, 0, function() {$(this).hide(); $(this).css('opacity', 1)});
        }
      }, 200);
      });
    });
<% end %>

</script>

<%= javascript_include_tag 'raphael' %>
<%= javascript_include_tag 'pie-chart', plugin: :usability %>
<%= javascript_include_tag 'usability.js', plugin: :usability %>
<%= stylesheet_link_tag 'usability.css', plugin: :usability %>
<%= javascript_include_tag 'usability_clipboard', plugin: :usability if settings['use_copy_from_clipboard'] %>

<% if ['issues', 'sd_requests', 'kpi', 'kpi_user_surcharges', 'rm_news'].include?(controller.controller_name) %>
  <%= javascript_include_tag 'jquery.magnific-popup.min.js', plugin: :usability %>
  <%= stylesheet_link_tag 'magnific-popup.css', plugin: :usability %>
<% end %>

<% if settings['use_autosave_fields'] %>
  <%= javascript_include_tag 'fields_autosave', plugin: :usability %>
<% end %>

<% if settings['use_custom_project_members_form'] && controller_name == 'projects' && action_name == 'settings'%>
  <script type="text/javascript" charset="utf-8">
    RMPlus.Usability.custom_project_members_form = "<%= j render partial: 'hooks/usability/members_form' %>";

    $(document).ready(function () {
      <% if !settings['enable_ajax_project_settings'] || params[:tab] == 'members' %>
        RMPlus.Usability.use_custom_project_members_form();
      <% end %>

      $(document.body).on("click", "#tab-content-members a[data-method='delete']", function() {
        jQuery(document.body).data('ajax_emmiter', jQuery(this));
        $.ajax({
          method: "DELETE",
          url: this.href,
          dataType: "script"
        }).always(function() {
          RMPlus.Usability.use_custom_project_members_form();
        });
        return false;
      });
      $(document.body).on("submit", "#add_members_to_project, #edit_membership", function(e) {
        $.ajax({
          method: "POST",
          url: this.action,
          data: $(this).serialize(),
          dataType: "script"
        }).always(function() {
          RMPlus.Usability.use_custom_project_members_form();
        });
        e.preventDefault();
        return false;
      });
    });
  </script>
<% end %>


<% if settings['show_sidebar_close_button'].to_s != '' && settings['usability_sidebar_width'].to_i > 0 %>
  <style type="text/css">
    #content {
      margin-right: <%= settings['usability_sidebar_width'].to_i + settings['usability_sidebar_gap'].to_i %>px;
      width: auto;
    }
    #sidebar {
      width: <%= settings['usability_sidebar_width'].to_i %>px;
    }
  </style>
<% end %>

<% if settings['hide_toolbar_for_wiki_textareas'] %>
  <style type="text/css">
  .jstElements
    {
    display: none;
    }
  </style>
<% end %>
<% if controller_name == 'issues' && @issue && @use_static_date_in_history %>
  <script type="text/javascript">
    $(document).ready(function() {
      var author = $('.issue > .author');
      author.filter(function(){return $(this).prev().hasClass('subject') }).html("<%= escape_javascript(authoring(@issue.created_on, @issue.author)) %>. <% if @issue.created_on != @issue.updated_on %><%= escape_javascript(l(:label_usability_updated_time, time_tag([@issue.updated_on, true]))).html_safe %>.<% end %>");
    });
  </script>
<% end %>

<% if User.current.logged? && (settings['fast_link_top_page'] || {})['text'].present? %>
    <script type="text/javascript" charset="utf-8">
      $(document).ready(function () {
        var fast_link = '<div id="us_fast_link_top_page_block" style="float: right;">';
        fast_link += '<%= escape_javascript(link_to("<span>#{(settings['fast_link_top_page'] || {})['text']}</span>".html_safe, (settings['fast_link_top_page'] || {})['url'], class: "#{(settings['fast_link_top_page'] || {})['icon']} #{(settings['fast_link_top_page'] || {})['icon'].start_with?('fa-') ? 'rm-icon' : 'us_icon'}", style: "color: #{(settings['fast_link_top_page'] || {})['color']}")) %>';
        fast_link += '</div>';
        fast_link = $(fast_link);
        $('#header h1').before(fast_link);
        fast_link.find(' a > span').css('border-bottom-color', fast_link.find('a').css('color').split(')')[0] + ', 0.40)');
      });
    </script>
<% end %>

app/views/hooks/usability/_members_form.html.erb
<% if (Setting.plugin_usability || {})['use_custom_project_members_form'] %>
  <%= form_tag project_memberships_path(@project), id: 'add_members_to_project', remote: true, method: :post do  %>
    <div style="display: inline-block; vertical-align: top; margin-bottom: 10px;">
      <label for="principals_for_new_member"><%= l(:label_user_plural) %></label>
      <br>
      <%= select_tag( 'membership[user_ids][]',
                      options_for_select(Principal.active.sorted.not_member_of(@project).visible.map {|m| [m.name, m.id]}, nil),
                      {class: 'select2_members', id: 'principals_for_new_member', multiple: true} ) %>
    </div>
    <div style="display: inline-block; padding-left: 10px; vertical-align: top; margin-bottom: 10px;">
      <label for="roles_for_new_members"><%= l(:label_role_plural) %></label>
      <br>
      <%= select_tag( 'membership[role_ids][]',
                      options_for_select(User.current.managed_roles(@project).map {|r| [r.name, r.id]}, nil),
                      {class: 'select2_roles', id: 'roles_for_new_members',  multiple: true} ) %>
    </div>
    <div style="display: inline-block; padding-left: 10px; vertical-align: top; padding-top: 3px;" class="buttons">
      <%= submit_tag l(:button_add), :id => 'member-add-submit', style: 'height: 27px;' %>
    </div>
  <% end %>
  <script type="text/javascript" charset="utf-8">
      $('.select2_members').select2({
          width: 320,
          placeholder: ' ',
          allowClear: true,
          ajax: {
              url: "<%= url_for(controller: :projects, action: :not_member_principal, project_id: @project.id) %>",
              dataType: 'json',
              delay: 200,
              data: function (params) {
                  return {q: params.term};
              },
              processResults: function(data, params) {
                  return { results: data };
              }
          }
      });

      $('.select2_roles').select2({
          width: 320,
          allowClear: true
      });
  </script>
<% end %>

app/views/hooks/usability/_us_view_projects_settings_members_bottom.html.erb
RMPlus.Usability.use_custom_project_members_form();

app/views/hooks/usability/_view_custom_fields_form_upper_box.html.erb
<% if custom_field.is_a?(IssueCustomField) && custom_field.field_format == 'list' %>
  <p>
    <%= form.check_box :us_store_for_new %>
  </p>
<% end %>

app/views/projects/_members_box.html.erb
  <% if @users_by_role.any? %>
  <div class="members box">
    <h3><%=l(:label_member_plural)%></h3>
    <ul>
    <% @users_by_role.keys.sort.each do |role| %>
      <li><%=h role %>
      <ul><li><%= @users_by_role[role].sort.collect{|u| link_to_user u}.join('</li><li>').html_safe %></li></ul>
      </li>
    <% end %>
    </ul>

  </div>
  <% end %>

app/views/projects/settings.js.erb
<% if @us_async_tab.present? %>
  $('#tab-content-<%= @us_async_tab[:name] %>').html('');
  $('#tab-content-<%= @us_async_tab[:name] %>').append('<%= escape_javascript(render(partial: @us_async_tab[:partial], locals: { tab: @us_async_tab })) %>');
  <% hook_name = @us_async_tab[:name].to_s.gsub(' ', '_').underscore %>
  <% if hook_name.present? %>
    <% hook_name = "us_view_projects_settings_#{hook_name}_bottom".to_sym %>
    <%= call_hook(hook_name, project: @project) %>
  <% end %>
<% end %>

app/views/projects/settings/_us_blank_async.html.erb
<div class="big_loader form_loader"></div>

app/views/settings/_rmplus_logo.html.erb
<% path_array = File.dirname(__FILE__).split("/") %>
<% plugin_name = path_array.fetch(path_array.index("plugins") + 1) %>

<div id="rmplus-logo" style="text-align: left; margin-top: 10px;">
  <div>
  <%= image_tag 'logo.png', plugin: plugin_name, alt: l(:label_rmplus_logo), title: l(:label_rmplus_logo), width: 50, style: 'vertical-align: bottom;' %>
  <span style="font-size: 10pt; margin-left: 5px;">
    <%= l(:label_rmplus_logo) %>&nbsp<a href="http://rmplus.pro">http://rmplus.pro</a>.
  </span>
  </div>
</div>

app/views/usability/_attachments_links.html.erb
<%
   tab ||= {}
   attachments ||= tab[:attachments] || []
   options ||= tab[:options] || {}
   thumbnails ||= tab[:thumbnails]
   container ||= tab[:container]
%>

<%= render partial: 'attachments/links', locals: { container: container, attachments: attachments, options: options, thumbnails: thumbnails } %>